name: Prettier

on:
  push:
  pull_request:
  merge_group:

jobs:
  prettier:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: npm

      - run: npm ci

      - name: Check formatting
        run: npx prettier . --check
